# Generated by Django 4.2 on 2023-05-07 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cakeapp', '0002_remove_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='CommentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeapp.post')),
            ],
            options={
                'verbose_name': 'Комментарий к посту',
                'verbose_name_plural': 'Комментарии к постам',
            },
        ),
        migrations.CreateModel(
            name='CommentRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Комментарий к посту',
                'verbose_name_plural': 'Комментарии к постам',
            },
        ),
        migrations.CreateModel(
            name='Cooker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Россия', max_length=100)),
                ('city', models.CharField(default='Москва', max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default_cook.jpg', upload_to='profile_pics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Кондитер',
                'verbose_name_plural': 'Кондитеры',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Россия', max_length=100)),
                ('city', models.CharField(default='Москва', max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('yearOfBirth', models.CharField(max_length=4)),
                ('image', models.ImageField(default='default_cust.png', upload_to='profile_pics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='Filling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(default='default_fil.jpg', upload_to='fillings_pics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeapp.cooker')),
            ],
            options={
                'verbose_name': 'Начинка',
                'verbose_name_plural': 'Начинки',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('image_post', models.ImageField(upload_to='recipe_pics')),
                ('video_url', models.URLField(blank=True, help_text='URL видео', null=True, verbose_name='URL видео')),
                ('doc_url', models.URLField(blank=True, help_text='URL текста рецепта', verbose_name='URL текста рецепта')),
                ('status', models.IntegerField(choices=[(0, 'Черновик'), (1, 'Опубликовано'), (2, 'На модерации')], default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cakeapp.category')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='ReplyCommentRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeapp.commentrecipe')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeapp.recipe')),
            ],
            options={
                'verbose_name': 'Ответ на комментарий к посту',
                'verbose_name_plural': 'Ответы на комментарии к постам',
            },
        ),
        migrations.CreateModel(
            name='ReplyCommentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeapp.commentpost')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeapp.post')),
            ],
            options={
                'verbose_name': 'Ответ на комментарий к посту',
                'verbose_name_plural': 'Ответы на комментарии к постам',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cakeapp.type'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeapp.cooker'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default='1')),
                ('cooker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cakeapp.cooker')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeapp.customer')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Черновик'), (1, 'Опубликовано'), (2, 'На модерации')], default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cakeapp.category')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cakeapp.type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeapp.cooker')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=11)),
                ('adress', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=11)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('date_need', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Черновик'), (1, 'Опубликовано'), (2, 'На модерации')], default=0)),
                ('cooker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeapp.cooker')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeapp.customer')),
                ('filling', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cakeapp.filling')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cakeapp.product')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('text_feed', models.TextField()),
                ('cooker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cakeapp.cooker')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeapp.customer')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='commentrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeapp.recipe'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeapp.cooker'),
        ),
    ]
