# Generated by Django 4.2 on 2023-05-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0003_category_commentpost_commentrecipe_cooker_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'Черновик'), (1, 'Опубликовано'), (2, 'На модерации')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[(0, 'Черновик'), (1, 'Опубликовано'), (2, 'На модерации')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[(0, 'Черновик'), (1, 'Опубликовано'), (2, 'На модерации')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[(0, 'Черновик'), (1, 'Опубликовано'), (2, 'На модерации')], default=0, max_length=1),
        ),
    ]
