# Generated by Django 4.2 on 2023-05-08 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0005_alter_order_status_alter_post_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='cooker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeapp.cooker'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='cooker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeapp.cooker'),
        ),
    ]
